CSC=csc

SRC= \
  Test/Program.cs \
  WiseUnpacker/Files/Microsoft/Constants.cs \
  WiseUnpacker/Files/Microsoft/Enums.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_DATA_DIRECTORY.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_DOS_HEADER.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_FILE_HEADER.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_OPTIONAL_HEADER.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_OS2_HEADER.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_RESOURCE_DATA_ENTRY.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_RESOURCE_DIRECTORY.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_RESOURCE_DIRECTORY_ENTRY.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_RESOURCE_DIR_STRING_U.cs \
  WiseUnpacker/Files/Microsoft/IMAGE_SECTION_HEADER.cs \
  WiseUnpacker/Files/Microsoft/NAMEINFO.cs \
  WiseUnpacker/Files/Microsoft/NewRlc.cs \
  WiseUnpacker/Files/Microsoft/NewRlcInfo.cs \
  WiseUnpacker/Files/Microsoft/NewRsrc.cs \
  WiseUnpacker/Files/Microsoft/NewSeg.cs \
  WiseUnpacker/Files/Microsoft/NewSegdata.cs \
  WiseUnpacker/Files/Microsoft/ResourceTable.cs \
  WiseUnpacker/Files/Microsoft/RsrcNameInfo.cs \
  WiseUnpacker/Files/Microsoft/RsrcString.cs \
  WiseUnpacker/Files/Microsoft/RsrcTypeInfo.cs \
  WiseUnpacker/Files/Microsoft/TYPEINFO.cs \
  WiseUnpacker/Files/MultiPartFile.cs \
  WiseUnpacker/Files/ReadOnlyFile.cs \
  WiseUnpacker/FormatProperty.cs \
  WiseUnpacker/Inflation/CRC32.cs \
  WiseUnpacker/Inflation/Inflate.cs \
  WiseUnpacker/Inflation/InflateImpl.cs \
  WiseUnpacker/WiseUnpacker.cs

all:
	$(CSC) -out:WiseUnpacker.exe $(SRC)

